//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookManagementDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiMuon
    {
        public string MaDG { get; set; }
        public string TenDG { get; set; }
        public Nullable<bool> Gioitinh { get; set; }
        public Nullable<System.DateTime> Ngaymuon { get; set; }
        public string Diachi { get; set; }
    }
}
