//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookManagementDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        public string Masach { get; set; }
        public string Tensach { get; set; }
        public string MaLoai { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string MaTG { get; set; }
    
        public virtual LoaiSach LoaiSach { get; set; }
        public virtual TacGia TacGia { get; set; }
    }
}
